#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

brightness="100
80
60
40
20"

value=$(menu "Option: " "$brightness")

# notify-send "Brightness:" "Setting brightness to $value"
xbacklight = $value

