#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

expr=$($DMENU -p "Expression: " <<< "")

while [[ -n "$expr" ]]; do
    expr=$($HOME/bin/menu/lib/calc.py "$expr")
    expr=$($DMENU -p "$expr: " <<< "")
done

