#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

expr=$($MenuCmd --prompt "Expression: " <<< "")

while [[ -n "$expr" ]]; do
    expr=$($HOME/bin/menu/lib/calc.py "$expr")
    expr=$($MenuCmd --prompt "$expr: " <<< "")
done
