#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

current=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
# read -r available < /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
available=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | sed 's/ /\n/g')
gov=$(printf "$available" | $DMENU -p "[$current] Governors: ")

if [[ -z $gov ]]; then
    exit
else
    sudo -A cpupower frequency-set -g $gov
fi

