#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

mainMenu="[Chapter]
[DvdNav]
[Nav+MouseMovement]"

action=$(menu "Option: " "$mainMenu")
case "$action" in
    *'Chapter'*)
        chapter=$(menu "Chapter #:")
        $(mpv dvd://$chapter)
    ;;
    *'DvdNav'*)
        $(mpv dvdnav://)
    ;;
    *'Nav+MouseMovement'*)
        $(mpv -mouse-movements dvdnav://)
    ;;
esac

