#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

cd /home/sanford/

file=1
while [ "$file" ]; do
    file=$(ls -1 --group-directories-first | $DMENU -l 10 -p "$(pwd) > ")
    if [ -e "$file" ]; then
        owd=$(pwd)
        if [ -d "$file" ]; then
            cd "$file"
        else [ -f "$file" ]
            if which xdg-open &> /dev/null; then
                exec xdg-open "$owd/$file" & disown
                unset file
            fi
        fi
    fi
done
