#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

# Select with dmenu
selection=$(ps -ef | sed 1d | $MenuCmd | awk '{print $2}' | tr '\n' ' ')
[ -z "$selection" ] && exit

notify-send "Killing Process:" "$selection"
kill "$selection"

