#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

menuchoices=$(find "$HOME/bin/menu/"  -maxdepth 1 -type f -exec basename {} \;)

choice=$(echo "$menuchoices" | $MenuCmd --prompt "Option: ")
[ "$choice" ] && $("$HOME/bin/menu/$choice")
