#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

menuchoices=$(find "$HOME/bin/menu/"  -maxdepth 1 -type f -exec basename {} \;)

choice=$(echo "$menuchoices" | $DMENU -p "Option: ")
[ "$choice" ] && $("$HOME/bin/menu/$choice")
