#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

# Menu Items
options="[Laptop]
[External]
[MainLeft]
[MainRight]"
# [On]
# [Off]"

action=$(menu "Option: " "$options")
case "$action" in
    *'Laptop'*)
        xrandr --output LVDS1 --mode 1366x768
        xrandr --output VGA1 --off
    ;;
    *'External'*)
        xrandr --output LVDS1 --off
        xrandr --output VGA1 --mode 1920x1080
    ;;
    *'MainLeft'*)
        xrandr --output LVDS1 --mode 1366x768 --left-of VGA1 --primary
        xrandr --output VGA1 --mode 1920x1080
    ;;
    *'MainRight'*)
        xrandr --output LVDS1 --mode 1366x768 --right-of VGA1 --primary
        xrandr --output VGA1 --mode 1920x1080
    ;;
    # *'On'*)
    #     xset dpms force on
    # ;;
    # *'Off'*)
    #     xset dpms force off
    # ;;
esac

