#!/bin/sh

source $HOME/bin/menu/lib/dmenu_helpers.sh

netchoices="$(netctl list)"
other="
[Wifi-Menu]"

choice="$(echo "$netchoices $other" | $DMENU -l 4 -p "Option: ")"
[ -z "$choice" ] && exit

if [[ "$choice" == "[Wifi-Menu]" ]]; then
    urxvtc -e sh -c "sudo wifi-menu"
else
    $choice = $(echo "$choice" | cut -c 3-)
    sudo netctl switch-to "$choice"
fi
