#!/bin/sh

source $HOME/bin/menu/lib/dmenu_helpers.sh

netchoices=$(find /etc/netctl/ -maxdepth 1 -mindepth 1 -type f)
other="
[Wifi-Select]"

choice="$(echo "$netchoices $other" | $DMENU -p "Option: ")"
[ -z "$choice" ] && exit

if [[ "$choice" == "[Wifi-Select]" ]]; then
    urxvtc -e "sudo wifi-select"
else
    sudo netctl start "$choice"
fi
