#!/bin/sh
# Dmenu shutdown menu.
# This script assumes you can run "netctl" as a user through sudo without
# entering a password. This can be done by editing /etc/sudoers via visudo.

source $HOME/bin/menu/lib/dmenu_helpers.sh

netchoices="$(netctl list)"
other="
[Wifi-Menu]"

choice="$(echo "$netchoices $other" | $DMENU -l 10 -p "Option: ")"
[ -z "$choice" ] && exit

if [[ "$choice" == "[Wifi-Menu]" ]]; then
    $TERMINAL -e sh -c "sudo wifi-menu"
else
    $choice = $(echo "$choice" | cut -c 3-)
    sudo netctl switch-to "$choice"
fi
