#!/bin/sh

source $HOME/bin/menu/lib/menu_helpers.sh

# # Common dmenu settings
# source $HOME/bin/menu/lib/dmenurc

# dmenu_run $options

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
    cache=$cachedir/dmenu_run
else
    cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

# Build Cache
if stest -dqr -n "$cache" $PATH; then
    stest -flx $PATH | sort -u > "$cache"
fi

app=$($MenuCmd < "$cache")

# [ -n $app ] && exec $app & disown
exec $app
