#!/bin/sh

# Common dmenu settings
source $HOME/bin/menu/lib/dmenurc

# dmenu_run $options

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
    cache=$cachedir/dmenu_run
else
    cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

# Build Cache
IFS=:
if stest -dqr -n "$cache" $PATH; then
    stest -flx $PATH | sort -u > "$cache"
fi

# Restore IFS because font string in $DMENU contains ':'
IFS=$' \t\n'
app=$($DMENU < "$cache")

[ -n $app ] && exec $app & disown
