#!/bin/bash

# Dmenu shutdown menu.
# This script assumes you can run "shutdown" as a user through sudo without
# entering a password. This can be done by editing /etc/sudoers via visudo.
source $HOME/bin/menu/lib/menu_helpers.sh

mainMenu="[Shutdown]
[Reboot]
[Sleep]
[Cancel]"
#[Hibernate] #defunct
#[Lock]

pauseMenu="now
+60
+45
+30
+15
+10
+5
+3
+2
+1"

action=$(menu "Option: " "$mainMenu")
[ -z "$action" ] && exit

case "$action" in
    '[Shutdown]')
        pauseTime=$(menu "Pause:" "$pauseMenu")
        [ -z "$pauseTime" ] && exit

        notify-send "System:" "Shutdown scheduled - $pauseTime"
        sudo shutdown -P "$pauseTime"
    ;;
    '[Reboot]')
        pauseTime=$(menu "Pause:" "$pauseMenu")
        [ -z "$pauseTime" ] && exit

        notify-send "System:" "Reboot scheduled - $pauseTime"
        sudo shutdown -r "$pauseTime"
    ;;
    '[Sleep]')
        notify-send "System:" "Suspending now"
        sudo systemctl suspend
    ;;
    '[Cancel]')
        notify-send "System:" "Shutdown command cancelled"
        sudo shutdown -c
    ;;
esac

