#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

mainMenu="[Shutdown]
[Reboot]
[Sleep]"

action=$(menu "Option: " "$mainMenu")
[ -z "$action" ] && exit

case "$action" in
    '[Shutdown]')
        sudo systemctl poweroff
    ;;
    '[Reboot]')
        sudo systemctl reboot
    ;;
    '[Sleep]')
        sudo systemctl suspend
    ;;
esac
