#!/bin/bash

source $HOME/bin/menu/lib/dmenu_helpers.sh

feh_command="feh --bg-fill"
wallpaper_dir="$HOME/docs/wallpapers/current"
wallpaper_options=$(find $wallpaper_dir -maxdepth 1 -type f -exec basename {} \;)
other_options="[Random]
"

choice=$(echo "$other_options$wallpaper_options" | $DMENU -l 12 -p "Option: ")
[ -z "$choice" ] && exit

if [[ "$choice" == "[Random]" ]] ; then
    $feh_command $(find "$wallpaper_dir" -maxdepth 1 -type f | shuf -n1)
else
    $feh_command "$wallpaper_dir/$choice"
fi

