#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

windowname=$(echo "" | $MenuCmd --prompt "Window Search: ")
size=$(echo "" | $MenuCmd --prompt "Window Size: ")

wmctrl -r "$windowname" -e 0,0,0,$size
