#!/bin/sh

background="#1d1f21"
current_line="#282a2e"
selection="#373b41"
foreground="#c5c8c6"
comment="#707880"
red="#cc6666"
orange="#de935f"
yellow="#f0c674"
green="#b5bd68"
aqua="#8abeb7"
blue="#81a2be"
purple="#b294bb"

font="DroidSansFallback:bold:size=8"
options="-i -fn $font -nf $foreground -nb $background -sf $background -sb $purple"
DMENU="dmenu $options"
