#!/bin/bash

source $HOME/bin/menu/lib/menu_helpers.sh

menuchoices=$(find "$HOME/bin/menu/scripts/"  -maxdepth 1 -type f -exec basename {} \;)
choice=$(menu "Option: " "$menuchoices")

[ "$choice" ] && $("$HOME/bin/menu/scripts/$choice")
