#!/bin/bash

MENU_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $MENU_DIR/lib/menu_helpers.sh

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [[ -d "$cachedir" ]]; then
    cache=$cachedir/dmenu_run
else
    cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

IFS=:
if stest -dqr -n "$cache" $PATH; then
    cache=$(stest -flx $PATH | sort -u | tee "$cache")
    IFS=$' \t\n'
else
    IFS=$' \t\n'
    cache=$(<$cache)
fi

app=$(menu "Run: " "$cache" )

[[ -n $app ]] && exec "$app" & disown
