#!/bin/sh

source $HOME/bin/menu/lib/menu_helpers.sh

cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/dmenu_run
else
	cache=$HOME/.dmenu_cache # if no xdg dir, fall back to dotfile in ~
fi

IFS=:
if stest -dqr -n "$cache" $PATH; then
    candidates=$(stest -flx $PATH | sort -u | tee "$cache")
    IFS=$' \t\n'
    app=$(echo "$candidates" | $MenuProg $(getPromptOption) "Run: ")
else
    IFS=$' \t\n'
    app=$($MenuProg $(getPromptOption) "Run: " < "$cache")
fi

[[ -n $app ]] && exec $app & disown
