#!/bin/bash

wallpaper_dir="$HOME/docs/wallpapers/current"

MENU_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $MENU_DIR/lib/menu_helpers.sh

feh_command="feh --bg-fill"

wallpaper_files=$(find $wallpaper_dir -maxdepth 1 -type f -exec basename {} \;)
other_options="
[Random]"

choice=$(menu "File: " "$wallpaper_files $other_options")

[[ -z "$choice" ]] && exit

if [[ "$choice" == "[Random]" ]] ; then
    $feh_command $(find "$wallpaper_dir" -maxdepth 1 -type f | shuf -n1)
else
    $feh_command "$wallpaper_dir/$choice"
fi
