#!/bin/bash

MENU_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source $MENU_DIR/../lib/menu_helpers.sh

windowname=$(menu "WindowSearch: " "")
size=$(menu "Size: " "")

# windowname=$(echo "" | $MenuCmd --prompt "Window Search: ")
# size=$(echo "" | $MenuCmd --prompt "Window Size: ")

wmctrl -r "$windowname" -e 0,0,0,$size
